Repository computational-psychology/stimupy, pull requests merged in 2023-03, with the labels that each got.

#24 Reorganized (and updated) existing demos to fit new organization
  README.md
  docs/_templates/autosummary/stimuli.rst
  docs/reference/api.md
  docs/reference/demos/components/circulars.md
  docs/reference/demos/components/frames.md
  docs/reference/demos/components/radials.md
  docs/reference/demos/components/waves.md
  docs/reference/demos/illusions/mondrians.md
  docs/reference/demos/stimuli/benarys.md
  docs/reference/demos/stimuli/bullseyes.md
  docs/reference/demos/stimuli/checkerboards.md
  docs/reference/demos/stimuli/cornsweets.md
  docs/reference/demos/stimuli/cubes.md
  docs/reference/demos/stimuli/delboeufs.md
  docs/reference/demos/stimuli/dungeons.md
  docs/reference/demos/stimuli/gabors.md
  docs/reference/demos/stimuli/gratings.md
  docs/reference/demos/stimuli/hermanns.md
  docs/reference/demos/stimuli/mondrians.md
  docs/reference/demos/stimuli/mueller_lyers.md
  docs/reference/demos/stimuli/pinwheels.md
  docs/reference/demos/stimuli/plaids.md
  docs/reference/demos/stimuli/ponzos.md
  docs/reference/demos/stimuli/rings.md
  docs/reference/demos/stimuli/waves.md
  docs/reference/demos/stimuli/wedding_cakes.md
Labels: documentation, maintenance

#35 Waves, primarily angular
  stimupy/components/angulars.py
  stimupy/components/shapes.py
  stimupy/components/waves.py
  stimupy/papers/modelfest.py
  stimupy/stimuli/gabors.py
  stimupy/stimuli/pinwheels.py
  stimupy/stimuli/plaids.py
  stimupy/stimuli/waves.py
  tests/papers/RHS2007.json
Labels: bug

#45 Bugfix: angular frequency in cycles per image
  stimupy/components/waves.py
  stimupy/stimuli/waves.py
Labels: bug

#50 Bugfix: `whites`
  docs/reference/demos/stimuli/whites.md
  stimupy/papers/RHS2007.py
  stimupy/papers/domijan2015.py
  stimupy/papers/murray2020.py
  stimupy/stimuli/whites.py
  stimupy/utils/utils.py
  tests/papers/RHS2007.json
Labels: bug, enhancement

#46 Docs: add remaining demos
  docs/reference/demos/stimuli/plaids.md
  docs/reference/demos/stimuli/sbcs.md
  docs/reference/demos/stimuli/todorovics.md
  docs/reference/demos/stimuli/waves.md
  stimupy/stimuli/todorovics.py
Labels: documentation

#68 Implement versioning
  .github/workflows/version.yml
  pyproject.toml
  stimupy/__init__.py
Labels: enhancement, maintenance
